name = "Server"
author = "Mou"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b7a16891491e68dbbf32b7278bb0735126232e7cfb416139cbca7b06159971b"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
